apiVersion: v1
kind: Service

metadata:
  name: monitoring-service
  labels:
    app: monitoring-app

spec:
  type: NodePort
  selector:
    app: monitoring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000